# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsLeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва документу')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name_plural': 'Документи',
                'verbose_name': 'Документ',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type_choices', models.CharField(choices=[('INSTR', 'Інструкція'), ('POL', 'Положення'), ('PROC', 'Процедура')], default='INSTR', help_text='Оберіть тип документу(інструкція, положення, процедура)', max_length=5, verbose_name='Тип документу')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
                ('text', tinymce.models.HTMLField(verbose_name='Зміст')),
            ],
            options={
                'verbose_name_plural': 'Документи',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва підрозділу')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
            ],
            options={
                'verbose_name_plural': 'Підрозділи',
                'verbose_name': 'Підрозділ',
            },
        ),
        migrations.AddField(
            model_name='leading',
            name='subdivision',
            field=models.ManyToManyField(to='docs.Subdivision', verbose_name='Підрозділ'),
        ),
        migrations.AddField(
            model_name='docsleading',
            name='leading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Leading'),
        ),
    ]
