# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsInstrukciy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва документу')),
                ('file', models.FileField(upload_to='docs/insrtukciy/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name_plural': 'Документи',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='LeadingInstrukciy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
                ('title', models.CharField(max_length=100, verbose_name='Назва процедури')),
                ('text', tinymce.models.HTMLField(verbose_name='Зміст процедури')),
            ],
            options={
                'verbose_name_plural': 'Процедури',
                'verbose_name': 'Процедура',
            },
        ),
        migrations.CreateModel(
            name='LeadingPolozhennya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
                ('title', models.CharField(max_length=100, verbose_name='Назва положення')),
                ('text', tinymce.models.HTMLField(verbose_name='Зміст положення')),
            ],
            options={
                'verbose_name_plural': 'Положення',
                'verbose_name': 'Положення',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва підрозділу')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
            ],
            options={
                'verbose_name_plural': 'Підрозділи',
                'verbose_name': 'Підрозділ',
            },
        ),
        migrations.AddField(
            model_name='leadingpolozhennya',
            name='subdivision',
            field=models.ManyToManyField(to='docs.Subdivision', verbose_name='Підрозділ'),
        ),
        migrations.AddField(
            model_name='leadinginstrukciy',
            name='subdivision',
            field=models.ManyToManyField(to='docs.Subdivision', verbose_name='Підрозділ'),
        ),
        migrations.AddField(
            model_name='docsinstrukciy',
            name='leading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.LeadingInstrukciy'),
        ),
    ]
