# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsPolozhennya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва документу')),
                ('file', models.FileField(upload_to='docs/insrtukciy/', verbose_name='Файл для скачування')),
                ('leading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.LeadingPolozhennya')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
    ]
