# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_docspolozhennya'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва документу')),
                ('file', models.FileField(upload_to='docs/insrtukciy/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name_plural': 'Документи',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='LeadingProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка')),
                ('title', models.CharField(max_length=100, verbose_name='Назва процедури')),
                ('text', tinymce.models.HTMLField(verbose_name='Зміст процедури')),
                ('subdivision', models.ManyToManyField(to='docs.Subdivision', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name_plural': 'Процедури',
                'verbose_name': 'Процедура',
            },
        ),
        migrations.AlterModelOptions(
            name='leadinginstrukciy',
            options={'verbose_name': 'Інструкція', 'verbose_name_plural': 'Інструкції'},
        ),
        migrations.AlterField(
            model_name='leadinginstrukciy',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Зміст інструкції'),
        ),
        migrations.AlterField(
            model_name='leadinginstrukciy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва інструкції'),
        ),
        migrations.AddField(
            model_name='docsprocedure',
            name='leading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.LeadingProcedure'),
        ),
    ]
