# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20160916_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinginstrukciy',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Зміст'),
        ),
        migrations.AlterField(
            model_name='leadinginstrukciy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
