# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(upload_to='insrtukciy/', verbose_name='Файл для скачування'),
        ),
    ]
