# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr', '0002_auto_20160912_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='leading',
            name='slug',
            field=models.SlugField(default=2, help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка'),
            preserve_default=False,
        ),
    ]
