# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instr', '0004_subdivision_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='slug',
            field=models.SlugField(help_text='Унікальне значення в адресній строці, добавляється автоматично.', max_length=255, unique=True, verbose_name='Адресна строка'),
        ),
    ]
